# Generated by Django 5.1.3 on 2024-11-28 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='pit_to_pilot',
            new_name='pit_to',
        ),
    ]
