# Generated by Django 5.1.3 on 2024-11-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_rename_pit_to_pilot_competition_pit_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitstopinfo',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AddField(
            model_name='pitstopinfo',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Завершено'),
        ),
    ]
