# Generated by Django 5.1.3 on 2024-11-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_pitstopinfo_active_pitstopinfo_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessioninfo',
            name='pilot_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Пилот'),
        ),
    ]
