# Generated by Django 5.1.3 on 2024-12-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_sessioninfo_fact_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitstopinfo',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Продолжительность пит-стопа'),
        ),
        migrations.AlterField(
            model_name='pitstopinfo',
            name='begin',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Начало пит-стопа, сек'),
        ),
        migrations.AlterField(
            model_name='pitstopinfo',
            name='end',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Конец пит-стопа, сек'),
        ),
    ]
